#!/bin/bash

# Processing HTML files that be generated by Sphinx. <http://code.google.com/p/princess-alist/>
# Copyright (C) 2010  xiaogaozi <gaochangjian@gmail.com>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

for file in "$@"; do
    filename=`basename $file`".sphinx"
    echo -n $file" ... "
    cp $file /tmp/$filename
    sed 's/&#822[01];/"/g' /tmp/$filename > $file && echo "OK"
    rm -f /tmp/$filename
done

exit 0
